### ISSUE TITLE
FileNotFoundError: dino_best_buddies/ dino_best_buddies_filter.pt

### ISSUE THREAD

**Issue by wuyiqii** [AssafSinger94/dino-tracker#2]
First of all, thank you for your wonderful work. I tried running python ./preprocessing/main_preprocessing.py \
--config ./config/preprocessing.yaml \
--data-path <VIDEO_DIR_PATH>，Is always unable to output the expected result correctly. Error message: FileNotFoundError: [Errno 2] No such file or directory:  '/dino-tracker/dataset/pig/dino_best_buddies/ dino_best_buddies_filter.pt '. How can I solve this problem
![WeChatebf3d9b35481703c7cf7335a26284d66](https://github.com/AssafSinger94/dino-tracker/assets/96756617/b8096650-57a0-4efa-9447-98513b87b91e)

**Comment by tnarek** [comment]
Hi @wuyiqii , thanks you your message!
Can you please send us the full output of running `main_preprocessing.py` ?
Since it comprises of running multiple sub-scripts, it is possible that one of them crashed, thus not creating the `dino_best_buddies_filtered.pt` file needed for the next subscript

**Comment by wuyiqii** [comment]
Thanks you your message! I run  main_preprocessing.py again processed a 780kb video, and here are the output: Traceback (most recent call last):
File "/share/data02/wuyiqidata/dino-tracker/./preprocessing/extract_trajectories.py", line 282, in <module>
save_trajectories(args)
File "/home/Wuyiqi/anaconda3/envs/dt/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
return func(*args, **kwargs)
File "/share/data02/wuyiqidata/dino-tracker/./preprocessing/extract_trajectories.py", line 185, in save_trajectories
masks, flows = get_flows_with_masks(
File "/home/Wuyiqi/anaconda3/envs/dt/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
return func(*args, **kwargs)
File "/share/data02/wuyiqidata/dino-tracker/./preprocessing/extract_trajectories.py", line 44, in get_flows_with_masks
flows = torch. zeros((2, len(images) - 1, 2, h, w), device=device)
RuntimeError: Trying to create tensor with negative dimension -1: [2, -1, 2, 476, 854]
----- Running python ./preprocessing/save_dino_embed_video.py --data-path /share/data02/wuyiqidata/dino-tracker/dataset/pig/ --config ./config/preprocessing.yaml
Traceback (most recent call last):
File "/share/data02/wuyiqidata/dino-tracker/./preprocessing/save_dino_embed_video.py", line 35, in <module>
save_dino_embed_video(args)
File "/share/data02/wuyiqidata/dino-tracker/./preprocessing/save_dino_embed_video.py", line 20, in save_dino_embed_video
video = load_video(video_folder=video_folder, resize=(h, w), num_frames=400).to(device) # T x 3 x H x W
File "/share/data02/wuyiqidata/dino-tracker/data/data_utils.py", line 104, in load_video
return torch.stack(video)
RuntimeError: stack expects a non-empty TensorList
----- Running python ./preprocessing/save_dino_embed_video.py --data-path /share/data02/wuyiqidata/dino-tracker/dataset/pig/ --config ./config/preprocessing. yaml --for-mask
Traceback (most recent call last):
File "/share/data02/wuyiqidata/dino-tracker/./preprocessing/save_dino_embed_video.py", line 35, in <module>
save_dino_embed_video(args)
File "/share/data02/wuyiqidata/dino-tracker/./preprocessing/save_dino_embed_video.py", line 20, in save_dino_embed_video
video = load_video(video_folder=video_folder, resize=(h, w), num_frames=400).to(device) # T x 3 x H x W
File "/share/data02/wuyiqidata/dino-tracker/data/data_utils.py", line 104, in load_video
return torch.stack(video)
RuntimeError: stack expects a non-empty TensorList
<img width="1179" alt="image" src="https://github.com/AssafSinger94/dino-tracker/assets/96756617/ce8ea7a0-6763-460c-bfc3-03e2960eee56">

**Comment by tnarek** [comment]
it seems the first error occurred when extracting the trajectories. I suspect either the path to the dataset is not correct, or the dataset folder does not contain any `jpg` or `png` files ?

**Comment by Ivandanilovich** [comment]
I got this error on windows. 
Problem is that line ```images = list(input_folder.glob("*.jpg")) + list(input_folder.glob("*.png"))``` is not find images. File extract_trajectories.py. 
Need to convert linux path format to windows like ```input_path = input_path.replace('\\', '/')```

**Comment by tnarek** [comment]
thanks @Ivandanilovich , I'm closing this issue for now. If there'll be further questions please feel free to repoen it.

**Comment by wyclearnpy** [comment]
I also encountered this problem, what should I do to solve it?
Traceback (most recent call last):
  File "/root/dino-tracker/./preprocessing/extract_trajectories.py", line 282, in <module>
    save_trajectories(args)
  File "/root/miniconda3/envs/dino-tracker/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/dino-tracker/./preprocessing/extract_trajectories.py", line 185, in save_trajectories
    masks, flows = get_flows_with_masks(
  File "/root/miniconda3/envs/dino-tracker/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/dino-tracker/./preprocessing/extract_trajectories.py", line 44, in get_flows_with_masks
    flows = torch.zeros((2, len(images) - 1, 2, h, w), device=device)
RuntimeError: Trying to create tensor with negative dimension -1: [2, -1, 2, 476, 854]
----- Running python ./preprocessing/save_dino_embed_video.py --data-path ./dataset/hursejump --config ./config/preprocessing.yaml
Traceback (most recent call last):
  File "/root/dino-tracker/./preprocessing/save_dino_embed_video.py", line 35, in <module>
    save_dino_embed_video(args)
  File "/root/dino-tracker/./preprocessing/save_dino_embed_video.py", line 20, in save_dino_embed_video
    video = load_video(video_folder=video_folder, resize=(h, w), num_frames=400).to(device) # T x 3 x H x W
  File "/root/dino-tracker/data/data_utils.py", line 104, in load_video
    return torch.stack(video)
RuntimeError: stack expects a non-empty TensorList
----- Running python ./preprocessing/save_dino_embed_video.py --data-path ./dataset/hursejump --config ./config/preprocessing.yaml --for-mask
Traceback (most recent call last):
  File "/root/dino-tracker/./preprocessing/save_dino_embed_video.py", line 35, in <module>
    save_dino_embed_video(args)
  File "/root/dino-tracker/./preprocessing/save_dino_embed_video.py", line 20, in save_dino_embed_video
    video = load_video(video_folder=video_folder, resize=(h, w), num_frames=400).to(device) # T x 3 x H x W
  File "/root/dino-tracker/data/data_utils.py", line 104, in load_video
    return torch.stack(video)
RuntimeError: stack expects a non-empty TensorList
----- Running python ./preprocessing/create_fg_mask.py --dino-embed-video-path ./dataset/hursejump/dino_embeddings/dino_embed_video-layer=23.pt --h 476 --w 854 --mask-path ./dataset/hursejump/masks --fg_mask_threshold 0.6
Traceback (most recent call last):
  File "/root/dino-tracker/./preprocessing/create_fg_mask.py", line 72, in <module>
    run(args)
  File "/root/miniconda3/envs/dino-tracker/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/dino-tracker/./preprocessing/create_fg_mask.py", line 52, in run
    dino_embed_video = torch.load(args.dino_embed_video_path) # T x C x H x W
  File "/root/miniconda3/envs/dino-tracker/lib/python3.9/site-packages/torch/serialization.py", line 986, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/root/miniconda3/envs/dino-tracker/lib/python3.9/site-packages/torch/serialization.py", line 435, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/root/miniconda3/envs/dino-tracker/lib/python3.9/site-packages/torch/serialization.py", line 416, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './dataset/hursejump/dino_embeddings/dino_embed_video-layer=23.pt'
----- Running python ./preprocessing/split_trajectories_to_fg_bg.py --traj_path ./dataset/hursejump/of_trajectories/trajectories.pt --fg_masks_path ./dataset/hursejump/masks --fg_traj_path ./dataset/hursejump/of_trajectories/fg_trajectories.pt --bg_traj_path ./dataset/hursejump/of_trajectories/bg_trajectories.pt
Traceback (most recent call last):
  File "/root/dino-tracker/./preprocessing/split_trajectories_to_fg_bg.py", line 95, in <module>
    split_trajectories_to_fg_bg(args)
  File "/root/dino-tracker/./preprocessing/split_trajectories_to_fg_bg.py", line 81, in split_trajectories_to_fg_bg
    mask_filter_trajectories(args.traj_path, args.fg_masks_path, args.fg_traj_path, filter_bg=False)
  File "/root/dino-tracker/./preprocessing/split_trajectories_to_fg_bg.py", line 56, in mask_filter_trajectories
    trajectories = torch.load(traj_path, map_location="cpu")
  File "/root/miniconda3/envs/dino-tracker/lib/python3.9/site-packages/torch/serialization.py", line 986, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/root/miniconda3/envs/dino-tracker/lib/python3.9/site-packages/torch/serialization.py", line 435, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/root/miniconda3/envs/dino-tracker/lib/python3.9/site-packages/torch/serialization.py", line 416, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './dataset/hursejump/of_trajectories/trajectories.pt'
----- Running python ./preprocessing_dino_bb/main_dino_bb_preprocessing.py --config ./config/preprocessing.yaml --data-path ./dataset/hursejump
----- Running python preprocessing_dino_bb/extract_dino_best_buddies.py --dino-emb-path ./dataset/hursejump/dino_embeddings/dino_embed_video.pt --stride 7 --out-path ./dataset/hursejump/dino_best_buddies/dino_best_buddies.pt --h 476 --w 854
/root/miniconda3/envs/dino-tracker/lib/python3.9/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3526.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Traceback (most recent call last):
  File "/root/dino-tracker/preprocessing_dino_bb/extract_dino_best_buddies.py", line 65, in <module>
    run(args)
  File "/root/miniconda3/envs/dino-tracker/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/dino-tracker/preprocessing_dino_bb/extract_dino_best_buddies.py", line 21, in run
    features = torch.load(dino_embed_video_path) # T x C x H x W
  File "/root/miniconda3/envs/dino-tracker/lib/python3.9/site-packages/torch/serialization.py", line 986, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/root/miniconda3/envs/dino-tracker/lib/python3.9/site-packages/torch/serialization.py", line 435, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/root/miniconda3/envs/dino-tracker/lib/python3.9/site-packages/torch/serialization.py", line 416, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './dataset/hursejump/dino_embeddings/dino_embed_video.pt'
----- Running python ./preprocessing/extract_trajectories.py --frames-path ./dataset/hursejump/video --output-path ./dataset/hursejump/of_trajectories/trajectories_wo_direct_filter.pt --min-trajectory-length 2 --threshold 1.5 --infer-res-size 476 854
Namespace(frames_path='./dataset/hursejump/video', output_path='./dataset/hursejump/of_trajectories/trajectories_wo_direct_filter.pt', infer_res_size=[476, 854], threshold=1.5, min_trajectory_length=2, filter_using_direct_flow=False, direct_flow_threshold=None)
Traceback (most recent call last):
  File "/root/dino-tracker/./preprocessing/extract_trajectories.py", line 282, in <module>
    save_trajectories(args)
  File "/root/miniconda3/envs/dino-tracker/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/dino-tracker/./preprocessing/extract_trajectories.py", line 185, in save_trajectories
    masks, flows = get_flows_with_masks(
  File "/root/miniconda3/envs/dino-tracker/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/dino-tracker/./preprocessing/extract_trajectories.py", line 44, in get_flows_with_masks
    flows = torch.zeros((2, len(images) - 1, 2, h, w), device=device)
RuntimeError: Trying to create tensor with negative dimension -1: [2, -1, 2, 476, 854]
----- Running python preprocessing_dino_bb/of_filter_dino_best_buddies.py --dino-bb-path ./dataset/hursejump/dino_best_buddies/dino_best_buddies.pt --traj-path ./dataset/hursejump/of_trajectories/trajectories_wo_direct_filter.pt --out-path ./dataset/hursejump/dino_best_buddies/dino_best_buddies_filtered.pt --dino-bb-stride 7 --h 476 --w 854
Traceback (most recent call last):
  File "/root/dino-tracker/preprocessing_dino_bb/of_filter_dino_best_buddies.py", line 124, in <module>
    run(args)
  File "/root/miniconda3/envs/dino-tracker/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/dino-tracker/preprocessing_dino_bb/of_filter_dino_best_buddies.py", line 45, in run
    bb_data = torch.load(dino_bb_path)
  File "/root/miniconda3/envs/dino-tracker/lib/python3.9/site-packages/torch/serialization.py", line 986, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/root/miniconda3/envs/dino-tracker/lib/python3.9/site-packages/torch/serialization.py", line 435, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/root/miniconda3/envs/dino-tracker/lib/python3.9/site-packages/torch/serialization.py", line 416, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './dataset/hursejump/dino_best_buddies/dino_best_buddies.pt'
----- Running python preprocessing_dino_bb/compute_dino_bb_nms.py --dino-bb-path ./dataset/hursejump/dino_best_buddies/dino_best_buddies_filtered.pt --dino-emb-path ./dataset/hursejump/dino_embeddings/dino_embed_video.pt --out-path ./dataset/hursejump/dino_best_buddies/dino_best_buddies_filtered.pt --stride 7 --box-size 30 --iou-thresh 0.2
Traceback (most recent call last):
  File "/root/dino-tracker/preprocessing_dino_bb/compute_dino_bb_nms.py", line 122, in <module>
    run(args)
  File "/root/dino-tracker/preprocessing_dino_bb/compute_dino_bb_nms.py", line 82, in run
    dino_bb = torch.load(args.dino_bb_path) # { 'i_j': { source_coords: [N x 2] } }
  File "/root/miniconda3/envs/dino-tracker/lib/python3.9/site-packages/torch/serialization.py", line 986, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/root/miniconda3/envs/dino-tracker/lib/python3.9/site-packages/torch/serialization.py", line 435, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/root/miniconda3/envs/dino-tracker/lib/python3.9/site-packages/torch/serialization.py", line 416, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './dataset/hursejump/dino_best_buddies/dino_best_buddies_filtered.pt'
