### ISSUE TITLE
'/data/yubowen/dino-tracker/dataset/horsejump/video/dino_embeddings/dino_embed_video-layer=23.pt'

### ISSUE THREAD

**Issue by xiyangyang99** [AssafSinger94/dino-tracker#37]
Using the horsejump dataset, after running main_preprocessing. py, only the of_trajections folder was generated and the dinoubest-buddes and dinoueembeddings folders in the readme file were not generated。
The output log is:
(omhand) [yubw@gpu1 dino-tracker]$ python main_preprocessing.py     --config ./config/preprocessing.yaml     --data-path /data/yubowen/dino-tracker/dataset/horsejump/video
----- Running python ./extract_trajectories.py --frames-path /data/yubowen/dino-tracker/dataset/horsejump/video/video --output-path /data/yubowen/dino-tracker/dataset/horsejump/video/of_trajectories/trajectories.pt --min-trajectory-length 2 --threshold 1.5 --infer-res-size 476 854 --filter-using-direct-flow --direct-flow-threshold 2.5
Namespace(frames_path='/data/yubowen/dino-tracker/dataset/horsejump/video/video', output_path='/data/yubowen/dino-tracker/dataset/horsejump/video/of_trajectories/trajectories.pt', infer_res_size=[476, 854], threshold=1.5, min_trajectory_length=2, filter_using_direct_flow=True, direct_flow_threshold=2.5)
XXXXXXXXXXXXXXXXXX /data/yubowen/dino-tracker/dataset/horsejump/video/video
Traceback (most recent call last):
  File "/data/yubowen/dino-tracker/./extract_trajectories.py", line 283, in <module>
    save_trajectories(args)
  File "/home/yubw/miniconda3/envs/omhand/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data/yubowen/dino-tracker/./extract_trajectories.py", line 186, in save_trajectories
    masks, flows = get_flows_with_masks(
  File "/home/yubw/miniconda3/envs/omhand/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data/yubowen/dino-tracker/./extract_trajectories.py", line 45, in get_flows_with_masks
    flows = torch.zeros((2, len(images) - 1, 2, h, w), device=device)
RuntimeError: Trying to create tensor with negative dimension -1: [2, -1, 2, 476, 854]
----- Running python ./save_dino_embed_video.py --data-path /data/yubowen/dino-tracker/dataset/horsejump/video --config ./config/preprocessing.yaml
Traceback (most recent call last):
  File "/data/yubowen/dino-tracker/./save_dino_embed_video.py", line 35, in <module>
    save_dino_embed_video(args)
  File "/data/yubowen/dino-tracker/./save_dino_embed_video.py", line 20, in save_dino_embed_video
    video = load_video(video_folder=video_folder, resize=(h, w), num_frames=400).to(device) # T x 3 x H x W
  File "/data/yubowen/dino-tracker/data/data_utils.py", line 104, in load_video
    return torch.stack(video)
RuntimeError: stack expects a non-empty TensorList
----- Running python ./save_dino_embed_video.py --data-path /data/yubowen/dino-tracker/dataset/horsejump/video --config ./config/preprocessing.yaml --for-mask
Traceback (most recent call last):
  File "/data/yubowen/dino-tracker/./save_dino_embed_video.py", line 35, in <module>
    save_dino_embed_video(args)
  File "/data/yubowen/dino-tracker/./save_dino_embed_video.py", line 20, in save_dino_embed_video
    video = load_video(video_folder=video_folder, resize=(h, w), num_frames=400).to(device) # T x 3 x H x W
  File "/data/yubowen/dino-tracker/data/data_utils.py", line 104, in load_video
    return torch.stack(video)
RuntimeError: stack expects a non-empty TensorList
----- Running python ./create_fg_mask.py --dino-embed-video-path /data/yubowen/dino-tracker/dataset/horsejump/video/dino_embeddings/dino_embed_video-layer=23.pt --h 476 --w 854 --mask-path /data/yubowen/dino-tracker/dataset/horsejump/video/masks --fg_mask_threshold 0.6
Traceback (most recent call last):
  File "/data/yubowen/dino-tracker/./create_fg_mask.py", line 72, in <module>
    run(args)
  File "/home/yubw/miniconda3/envs/omhand/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data/yubowen/dino-tracker/./create_fg_mask.py", line 52, in run
    dino_embed_video = torch.load(args.dino_embed_video_path) # T x C x H x W
  File "/home/yubw/miniconda3/envs/omhand/lib/python3.10/site-packages/torch/serialization.py", line 998, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/yubw/miniconda3/envs/omhand/lib/python3.10/site-packages/torch/serialization.py", line 445, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/yubw/miniconda3/envs/omhand/lib/python3.10/site-packages/torch/serialization.py", line 426, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/data/yubowen/dino-tracker/dataset/horsejump/video/dino_embeddings/dino_embed_video-layer=23.pt'
----- Running python ./split_trajectories_to_fg_bg.py --traj_path /data/yubowen/dino-tracker/dataset/horsejump/video/of_trajectories/trajectories.pt --fg_masks_path /data/yubowen/dino-tracker/dataset/horsejump/video/masks --fg_traj_path /data/yubowen/dino-tracker/dataset/horsejump/video/of_trajectories/fg_trajectories.pt --bg_traj_path /data/yubowen/dino-tracker/dataset/horsejump/video/of_trajectories/bg_trajectories.pt
Traceback (most recent call last):
  File "/data/yubowen/dino-tracker/./split_trajectories_to_fg_bg.py", line 95, in <module>
    split_trajectories_to_fg_bg(args)
  File "/data/yubowen/dino-tracker/./split_trajectories_to_fg_bg.py", line 81, in split_trajectories_to_fg_bg
    mask_filter_trajectories(args.traj_path, args.fg_masks_path, args.fg_traj_path, filter_bg=False)
  File "/data/yubowen/dino-tracker/./split_trajectories_to_fg_bg.py", line 56, in mask_filter_trajectories
    trajectories = torch.load(traj_path, map_location="cpu")
  File "/home/yubw/miniconda3/envs/omhand/lib/python3.10/site-packages/torch/serialization.py", line 998, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/yubw/miniconda3/envs/omhand/lib/python3.10/site-packages/torch/serialization.py", line 445, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/yubw/miniconda3/envs/omhand/lib/python3.10/site-packages/torch/serialization.py", line 426, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/data/yubowen/dino-tracker/dataset/horsejump/video/of_trajectories/trajectories.pt'
----- Running python ./main_dino_bb_preprocessing.py --config ./config/preprocessing.yaml --data-path /data/yubowen/dino-tracker/dataset/horsejump/video
----- Running python ./extract_dino_best_buddies.py --dino-emb-path /data/yubowen/dino-tracker/dataset/horsejump/video/dino_embeddings/dino_embed_video.pt --stride 7 --out-path /data/yubowen/dino-tracker/dataset/horsejump/video/dino_best_buddies/dino_best_buddies.pt --h 476 --w 854
/home/yubw/miniconda3/envs/omhand/lib/python3.10/site-packages/torch/functional.py:507: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3549.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Traceback (most recent call last):
  File "/data/yubowen/dino-tracker/./extract_dino_best_buddies.py", line 65, in <module>
    run(args)
  File "/home/yubw/miniconda3/envs/omhand/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data/yubowen/dino-tracker/./extract_dino_best_buddies.py", line 21, in run
    features = torch.load(dino_embed_video_path) # T x C x H x W
  File "/home/yubw/miniconda3/envs/omhand/lib/python3.10/site-packages/torch/serialization.py", line 998, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/yubw/miniconda3/envs/omhand/lib/python3.10/site-packages/torch/serialization.py", line 445, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/yubw/miniconda3/envs/omhand/lib/python3.10/site-packages/torch/serialization.py", line 426, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/data/yubowen/dino-tracker/dataset/horsejump/video/dino_embeddings/dino_embed_video.pt'
----- Running python ./extract_trajectories.py --frames-path /data/yubowen/dino-tracker/dataset/horsejump/video/video --output-path /data/yubowen/dino-tracker/dataset/horsejump/video/of_trajectories/trajectories_wo_direct_filter.pt --min-trajectory-length 2 --threshold 1.5 --infer-res-size 476 854
Namespace(frames_path='/data/yubowen/dino-tracker/dataset/horsejump/video/video', output_path='/data/yubowen/dino-tracker/dataset/horsejump/video/of_trajectories/trajectories_wo_direct_filter.pt', infer_res_size=[476, 854], threshold=1.5, min_trajectory_length=2, filter_using_direct_flow=False, direct_flow_threshold=None)
XXXXXXXXXXXXXXXXXX /data/yubowen/dino-tracker/dataset/horsejump/video/video
Traceback (most recent call last):
  File "/data/yubowen/dino-tracker/./extract_trajectories.py", line 283, in <module>
    save_trajectories(args)
  File "/home/yubw/miniconda3/envs/omhand/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data/yubowen/dino-tracker/./extract_trajectories.py", line 186, in save_trajectories
    masks, flows = get_flows_with_masks(
  File "/home/yubw/miniconda3/envs/omhand/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data/yubowen/dino-tracker/./extract_trajectories.py", line 45, in get_flows_with_masks
    flows = torch.zeros((2, len(images) - 1, 2, h, w), device=device)
RuntimeError: Trying to create tensor with negative dimension -1: [2, -1, 2, 476, 854]
----- Running python ./of_filter_dino_best_buddies.py --dino-bb-path /data/yubowen/dino-tracker/dataset/horsejump/video/dino_best_buddies/dino_best_buddies.pt --traj-path /data/yubowen/dino-tracker/dataset/horsejump/video/of_trajectories/trajectories_wo_direct_filter.pt --out-path /data/yubowen/dino-tracker/dataset/horsejump/video/dino_best_buddies/dino_best_buddies_filtered.pt --dino-bb-stride 7 --h 476 --w 854
Traceback (most recent call last):
  File "/data/yubowen/dino-tracker/./of_filter_dino_best_buddies.py", line 124, in <module>
    run(args)
  File "/home/yubw/miniconda3/envs/omhand/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data/yubowen/dino-tracker/./of_filter_dino_best_buddies.py", line 45, in run
    bb_data = torch.load(dino_bb_path)
  File "/home/yubw/miniconda3/envs/omhand/lib/python3.10/site-packages/torch/serialization.py", line 998, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/yubw/miniconda3/envs/omhand/lib/python3.10/site-packages/torch/serialization.py", line 445, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/yubw/miniconda3/envs/omhand/lib/python3.10/site-packages/torch/serialization.py", line 426, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/data/yubowen/dino-tracker/dataset/horsejump/video/dino_best_buddies/dino_best_buddies.pt'
----- Running python ./compute_dino_bb_nms.py --dino-bb-path /data/yubowen/dino-tracker/dataset/horsejump/video/dino_best_buddies/dino_best_buddies_filtered.pt --dino-emb-path /data/yubowen/dino-tracker/dataset/horsejump/video/dino_embeddings/dino_embed_video.pt --out-path /data/yubowen/dino-tracker/dataset/horsejump/video/dino_best_buddies/dino_best_buddies_filtered.pt --stride 7 --box-size 30 --iou-thresh 0.2
Traceback (most recent call last):
  File "/data/yubowen/dino-tracker/./compute_dino_bb_nms.py", line 122, in <module>
    run(args)
  File "/data/yubowen/dino-tracker/./compute_dino_bb_nms.py", line 82, in run
    dino_bb = torch.load(args.dino_bb_path) # { 'i_j': { source_coords: [N x 2] } }
  File "/home/yubw/miniconda3/envs/omhand/lib/python3.10/site-packages/torch/serialization.py", line 998, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/yubw/miniconda3/envs/omhand/lib/python3.10/site-packages/torch/serialization.py", line 445, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/yubw/miniconda3/envs/omhand/lib/python3.10/site-packages/torch/serialization.py", line 426, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/data/yubowen/dino-tracker/dataset/horsejump/video/dino_best_buddies/dino_best_buddies_filtered.pt'

**Comment by Erze-ee** [comment]
I have the same question , so how to get '.pt' files.

**Comment by tingjiesun** [comment]
> I have the same question , so how to get '.pt' files.

Hello, have you solved this problem? Can you tell me how to do it
