### ISSUE TITLE
python ./inference_grid.py --config ./config/train.yaml --data-path ./dataset/horsejump

### ISSUE THREAD

**Issue by Aiades** [AssafSinger94/dino-tracker#4]
(dino-tracker) C:\Users\Administrator\dino-tracker>python ./inference_grid.py --config ./config/train.yaml --data-path ./dataset/horsejump
Traceback (most recent call last):
  File "C:\Users\Administrator\dino-tracker\inference_grid.py", line 54, in <module>
    run(args)
  File "C:\Users\Administrator\.conda\envs\dino-tracker\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Administrator\dino-tracker\inference_grid.py", line 16, in run
    model = dino_tracker.get_model()
  File "C:\Users\Administrator\dino-tracker\dino_tracker.py", line 102, in get_model
    model = Tracker(**tracker_args).to(device)
  File "C:\Users\Administrator\dino-tracker\models\tracker.py", line 48, in __init__
    self.load_dino_embed_video()
  File "C:\Users\Administrator\.conda\envs\dino-tracker\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Administrator\dino-tracker\models\tracker.py", line 70, in load_dino_embed_video
    assert os.path.exists(self.dino_embed_path)
AssertionError

**Comment by tnarek** [comment]
hi @Aiades, can you please send the output of the preprocessing script?

**Comment by LiYan0306** [comment]
@tnarek ,I'd meet the same problem, here are all output.
![屏幕截图 2024-07-18 185540](https://github.com/user-attachments/assets/0d0c4a51-6c42-4ef3-b5dd-30188115e73d)
